'use client'

import { useEffect, useRef, useState, useTransition } from 'react'
import SignaturePadLib from 'signature_pad'
import { Button, Card, CardHeader, CardBody, CardFooter, Alert } from '@xxm/ui'
import { formatDate } from '@xxm/utils'

type SignatureMeta = {
  id: string
  displayName: string
  isActive: boolean
  nextChangeAllowedAt: string
  canChangeNow: boolean
  createdAt: string
  updatedAt: string
} | null

type LockStatus = { canChange: boolean; nextChangeAllowedAt: string | null }

type HistoryEntry = { id: string; signatureUrl: string; replacedAt: string }

interface SignaturePadCardProps {
  signature: SignatureMeta
  lockStatus: LockStatus
  history: HistoryEntry[]
  saveAction: (fd: FormData) => Promise<void>
}

export function SignaturePadCard({ signature, lockStatus, history, saveAction }: SignaturePadCardProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const padRef = useRef<SignaturePadLib | null>(null)
  const [mode, setMode] = useState<'draw' | 'upload'>('draw')
  const [uploadFile, setUploadFile] = useState<File | null>(null)
  const [displayName, setDisplayName] = useState(signature?.displayName ?? '')
  const [error, setError] = useState<string | null>(null)
  const [isPending, startTransition] = useTransition()

  const isLocked = signature !== null && !lockStatus.canChange

  useEffect(() => {
    if (mode !== 'draw' || !canvasRef.current || isLocked) return

    const canvas = canvasRef.current
    const ratio = Math.max(window.devicePixelRatio || 1, 1)
    canvas.width = canvas.offsetWidth * ratio
    canvas.height = canvas.offsetHeight * ratio
    canvas.getContext('2d')?.scale(ratio, ratio)

    const pad = new SignaturePadLib(canvas, {
      backgroundColor: 'rgb(255, 255, 255)',
      penColor: 'rgb(15, 61, 46)',
    })
    padRef.current = pad

    return () => pad.off()
  }, [mode, isLocked])

  const handleSubmit = () => {
    setError(null)

    const trimmedName = displayName.trim()
    if (trimmedName.length < 3 || trimmedName.length > 120) {
      setError('Display name must be between 3 and 120 characters.')
      return
    }

    startTransition(async () => {
      let file: File

      if (mode === 'upload') {
        if (!uploadFile) {
          setError('Please choose a PNG image to upload.')
          return
        }
        file = uploadFile
      } else {
        if (!padRef.current || padRef.current.isEmpty()) {
          setError('Please draw your signature.')
          return
        }
        const dataUrl = padRef.current.toDataURL('image/png')
        const blob = await (await fetch(dataUrl)).blob()
        file = new File([blob], 'signature.png', { type: 'image/png' })
      }

      const fd = new FormData()
      fd.set('signature', file)
      fd.set('displayName', trimmedName)
      fd.set('mode', signature ? 'update' : 'create')

      await saveAction(fd)
    })
  }

  return (
    <div className="space-y-6">
      {isLocked && signature && (
        <Alert variant="warning" title="Signature locked">
          Your signature can only be changed once every 90 days. Next change allowed on{' '}
          {formatDate(signature.nextChangeAllowedAt)}.
        </Alert>
      )}

      {error && <Alert variant="error">{error}</Alert>}

      <Card>
        <CardHeader
          title={signature ? 'Update authorisation signature' : 'Set up your authorisation signature'}
          description="This signature is embedded on official statements and PDFs generated by the system."
        />
        <CardBody className="space-y-4">
          {signature && (
            <div className="rounded-xl border border-xxm-gray-200 bg-xxm-champagne-50 px-4 py-3 text-sm">
              <p className="font-semibold text-xxm-green-900">Current signature</p>
              <p className="text-xxm-gray-600 mt-0.5">
                {signature.displayName} · last updated {formatDate(signature.updatedAt)}
              </p>
            </div>
          )}

          <div className="flex gap-2">
            <Button
              type="button"
              variant={mode === 'draw' ? 'primary' : 'outline'}
              size="sm"
              onClick={() => setMode('draw')}
              disabled={isLocked}
            >
              Draw signature
            </Button>
            <Button
              type="button"
              variant={mode === 'upload' ? 'primary' : 'outline'}
              size="sm"
              onClick={() => setMode('upload')}
              disabled={isLocked}
            >
              Upload image
            </Button>
          </div>

          {mode === 'draw' ? (
            <div className="space-y-2">
              <canvas
                ref={canvasRef}
                className="w-full h-48 rounded-xl border border-xxm-gray-200 bg-white touch-none"
              />
              <Button type="button" variant="ghost" size="sm" onClick={() => padRef.current?.clear()} disabled={isLocked}>
                Clear
              </Button>
            </div>
          ) : (
            <div className="space-y-2">
              <input
                type="file"
                accept="image/png"
                disabled={isLocked}
                onChange={(e) => setUploadFile(e.target.files?.[0] ?? null)}
                className="block w-full text-sm text-xxm-gray-600 file:mr-4 file:rounded-xl file:border-0 file:bg-xxm-green-50 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-xxm-green hover:file:bg-xxm-green-100"
              />
              <p className="text-xs text-xxm-gray-500">PNG only, up to 1MB.</p>
            </div>
          )}

          <div className="space-y-1.5">
            <label className="block text-xs font-medium text-xxm-gray-700">Display name *</label>
            <input
              value={displayName}
              onChange={(e) => setDisplayName(e.target.value)}
              maxLength={120}
              minLength={3}
              required
              disabled={isLocked}
              placeholder="e.g. Maluleke Kurhula Success — Treasurer"
              className="w-full rounded-xl border border-xxm-gray-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-xxm-green/25 disabled:bg-xxm-gray-50"
            />
            <p className="text-xs text-xxm-gray-500">
              Shown beneath your signature on generated statements and reports.
            </p>
          </div>
        </CardBody>
        <CardFooter>
          <Button type="button" onClick={handleSubmit} loading={isPending} disabled={isLocked}>
            {signature ? 'Update signature' : 'Save signature'}
          </Button>
        </CardFooter>
      </Card>

      {history.length > 0 && (
        <Card>
          <CardHeader title="Signature history" description="Previous signatures, most recent first." />
          <CardBody>
            <ul className="space-y-2">
              {history.map((entry) => (
                <li
                  key={entry.id}
                  className="flex items-center justify-between text-sm border-b border-xxm-gray-100 pb-2 last:border-0 last:pb-0"
                >
                  <span className="text-xxm-gray-600">Replaced {formatDate(entry.replacedAt)}</span>
                </li>
              ))}
            </ul>
          </CardBody>
        </Card>
      )}
    </div>
  )
}
