import { createEnv } from '@t3-oss/env-nextjs'
import { z } from 'zod'

export const env = createEnv({
  emptyStringAsUndefined: true,
  server: {
    DATABASE_URL: z.string().url(),
    NEXTAUTH_SECRET: z.string().min(32),
    NEXTAUTH_URL: z.string().url().optional(),
    FOUNDER_EMAIL: z.string().email().optional(),
    ENCRYPTION_KEY: z.string().length(64),
    NETCASH_SERVICE_KEY: z.string().min(1).optional(),
    NETCASH_WEBHOOK_SECRET: z.string().min(1).optional(),
    NETCASH_API_URL: z.string().url().default('https://ws.netcash.co.za/NSWSSX/NetcashTest.asmx'),
    BULKSMS_USERNAME: z.string().min(1).optional(),
    BULKSMS_PASSWORD: z.string().min(1).optional(),
    RESEND_API_KEY: z.string().min(1).optional(),
    RESEND_FROM_EMAIL: z.string().email().default('noreply@xkimmxamali.co.za'),
    INNGEST_EVENT_KEY: z.string().min(1).optional(),
    INNGEST_SIGNING_KEY: z.string().min(1).optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1).optional(),
    BLOB_READ_WRITE_TOKEN: z.string().min(1).optional(),
    WHATSAPP_GROUP_LINK: z.string().url().default('https://chat.whatsapp.com/EMFpa8pjiiCLHhO8Eg8pCb'),
    WHATSAPP_GROUP_NAME: z.string().default('Xkimm Xa Mali'),
    ADMIN_WHATSAPP_NUMBER: z.string().min(1).default('27810780859'),
    ENABLE_MANUAL_PAYMENTS: z.coerce.boolean().default(true),
    ENABLE_GOAL_LOCKING: z.coerce.boolean().default(true),
    // Sentry (build-time source-map upload; optional in dev)
    SENTRY_ORG: z.string().optional(),
    SENTRY_PROJECT: z.string().optional(),
    SENTRY_DSN: z.string().url().optional(),
    // Security tunables — allows per-environment adjustment without code changes
    MAX_LOGIN_ATTEMPTS: z.coerce.number().int().min(3).max(20).default(5),
    LOCKOUT_DURATION_MINUTES: z.coerce.number().int().min(5).max(1440).default(15),
    // Shared secret for internal admin→web API calls (server-to-server, no session needed)
    ADMIN_API_SECRET: z.string().min(32).optional(),
  },
  client: {
    NEXT_PUBLIC_SENTRY_DSN: z.string().url().optional(),
    NEXT_PUBLIC_ADMIN_URL: z.string().url().default('http://localhost:3002'),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    FOUNDER_EMAIL: process.env.FOUNDER_EMAIL,
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY,
    NETCASH_SERVICE_KEY: process.env.NETCASH_SERVICE_KEY,
    NETCASH_WEBHOOK_SECRET: process.env.NETCASH_WEBHOOK_SECRET,
    NETCASH_API_URL: process.env.NETCASH_API_URL,
    BULKSMS_USERNAME: process.env.BULKSMS_USERNAME,
    BULKSMS_PASSWORD: process.env.BULKSMS_PASSWORD,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
    INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
    INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN,
    WHATSAPP_GROUP_LINK: process.env.WHATSAPP_GROUP_LINK,
    WHATSAPP_GROUP_NAME: process.env.WHATSAPP_GROUP_NAME,
    ADMIN_WHATSAPP_NUMBER: process.env.ADMIN_WHATSAPP_NUMBER,
    ENABLE_MANUAL_PAYMENTS: process.env.ENABLE_MANUAL_PAYMENTS,
    ENABLE_GOAL_LOCKING: process.env.ENABLE_GOAL_LOCKING,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,
    SENTRY_DSN: process.env.SENTRY_DSN,
    MAX_LOGIN_ATTEMPTS: process.env.MAX_LOGIN_ATTEMPTS,
    LOCKOUT_DURATION_MINUTES: process.env.LOCKOUT_DURATION_MINUTES,
    ADMIN_API_SECRET: process.env.ADMIN_API_SECRET,
    NEXT_PUBLIC_SENTRY_DSN: process.env.NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_ADMIN_URL: process.env.NEXT_PUBLIC_ADMIN_URL,
  },
})
