import { NextRequest, NextResponse } from 'next/server'
import { auth } from '@/lib/auth'
import { getContributionsForExport } from '@/lib/services'
import { writeAuditLog } from '@/lib/services/shared'
import { adminExportRatelimit } from '@/lib/rate-limit'
import { clientIpFromHeaders } from '@xxm/utils/client-ip'

const MONTHS = [
  'January','February','March','April','May','June',
  'July','August','September','October','November','December',
]

function rands(n: number) {
  return `R ${n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ' ')}`
}

function csvCell(value: string | number | null | undefined): string {
  const str = value == null ? '' : String(value)
  if (/[",\n\r]/.test(str)) return `"${str.replace(/"/g, '""')}"`
  return str
}

export async function GET(req: NextRequest) {
  const session = await auth()
  const roles   = (session?.user?.roles as string[] | undefined) ?? []
  if (!session?.user?.id || !roles.includes('ADMIN')) {
    return new NextResponse('Forbidden', { status: 403 })
  }

  const { searchParams } = new URL(req.url)
  const monthRaw = parseInt(searchParams.get('month') ?? '', 10)
  const yearRaw  = parseInt(searchParams.get('year') ?? '', 10)

  if (!Number.isInteger(monthRaw) || monthRaw < 1 || monthRaw > 12 || !Number.isInteger(yearRaw) || yearRaw < 2024) {
    return new NextResponse('Missing or invalid month or year', { status: 400 })
  }
  const month = monthRaw
  const year  = yearRaw

  const { success } = await adminExportRatelimit.limit(session.user.id)
  if (!success) {
    return new NextResponse('Export limit reached. Please try again later.', { status: 429 })
  }

  const contributions = await getContributionsForExport(roles, month, year)

  // Recorded, because this is personal information leaving the system.
  //
  // Every other consequential act on this console writes an audit entry —
  // approving a mandate, changing somebody's status, reversing money. Taking a
  // copy of every member's name, email address and phone number wrote nothing,
  // so there was no way to answer who had done it or when. POPIA expects a
  // responsible party to be able to account for what happens to personal
  // information, and the Founder Guide's promise is that the history can be
  // retraced years later.
  //
  // Written before the file is returned, and awaited: a record that is
  // best-effort is a record that goes missing exactly when somebody is asking.
  await writeAuditLog({
    userId: session.user.id,
    action: 'ADMIN_CONTRIBUTIONS_EXPORTED',
    entity: 'Contribution',
    entityId: `${year}-${String(month).padStart(2, '0')}`,
    payload: { month, year, format: 'csv', records: contributions.length },
    ipAddress: clientIpFromHeaders(req.headers) ?? 'unknown',
  })

  const periodLabel = `${MONTHS[month - 1] ?? `Month ${month}`} ${year}`
  const generatedAt = new Date().toLocaleString('en-ZA', {
    day: 'numeric', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short',
  })

  const totalDue  = contributions.reduce((s, c) => s + Number(c.amountDue), 0)
  const totalPaid = contributions.reduce((s, c) => s + Number(c.amountPaid), 0)
  const outstanding = Math.max(0, totalDue - totalPaid)
  const paidCount   = contributions.filter((c) => c.status === 'PAID').length
  const collectionRate = contributions.length > 0
    ? Math.round((paidCount / contributions.length) * 100)
    : 0

  // Says what it is on the file itself. The member statement carries
  // "Confidential" on every page; a spreadsheet holding the whole membership's
  // names, email addresses and phone numbers carried nothing — and a CSV is far
  // more likely to be forwarded, dropped in a shared folder, or opened on a
  // phone than a PDF is. Naming who pulled it also means a leaked copy can be
  // traced back to a download rather than to a guess.
  const headerTitle = [
    `XKIMI XA MALI FOUNDATION — CONTRIBUTION REPORT`,
    `Period: ${periodLabel}`,
    `Generated: ${generatedAt}`,
    `Generated by: ${csvCell(session.user.email ?? session.user.id)}`,
    `CONFIDENTIAL — contains members' personal information. Do not forward outside the Foundation.`,
    '',
  ]

  const columnHeaders = [
    'Member Name',
    'Email Address',
    'Phone Number',
    'Amount Due (R)',
    'Amount Paid (R)',
    'Outstanding (R)',
    'Due Date',
    'Status',
  ].map(csvCell).join(',')

  const rows = contributions.map((c) => {
    const balance = Math.max(0, Number(c.amountDue) - Number(c.amountPaid))
    return [
      csvCell(`${c.user.firstName} ${c.user.lastName}`),
      csvCell(c.user.email),
      csvCell(c.user.phone),
      Number(c.amountDue).toFixed(2),
      Number(c.amountPaid).toFixed(2),
      balance.toFixed(2),
      csvCell(c.dueDate ? new Date(c.dueDate).toLocaleDateString('en-ZA') : ''),
      csvCell(c.status),
    ].join(',')
  })

  const summarySection = [
    '',
    '--- SUMMARY ---',
    `Period,${csvCell(periodLabel)}`,
    `Total Members,${contributions.length}`,
    `Members Paid,${paidCount}`,
    `Collection Rate,${collectionRate}%`,
    `Total Due,${rands(totalDue)}`,
    `Total Paid,${rands(totalPaid)}`,
    `Outstanding,${rands(outstanding)}`,
    `Generated,${csvCell(generatedAt)}`,
  ]

  const lines = [
    ...headerTitle,
    columnHeaders,
    ...rows,
    ...summarySection,
  ]

  const BOM      = '﻿'
  const csv      = BOM + lines.join('\r\n')
  const filename = `xkimi-xa-mali-report-${year}-${String(month).padStart(2, '0')}.csv`

  return new NextResponse(csv, {
    status: 200,
    headers: {
      'Content-Type':        'text/csv; charset=utf-8',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Cache-Control':       'no-store',
    },
  })
}
