import { db } from '@/lib/db'
import { MAX_MEMBERS } from '@xxm/utils'
import { refuseRoleChange, ROLE_CHANGE_REFUSAL_MESSAGE } from '@xxm/utils/role-policy'
import { publishRoleVersion } from '@/lib/role-version'
import { assertAdmin, writeAuditLog, AdminNotFoundError, AdminConflictError, AdminForbiddenError } from './shared'

// ─── The fifty-member cap ─────────────────────────────────────────────────────

/**
 * How many of the fifty places are taken — so leadership can see the headroom
 * before inviting, rather than discovering it by being refused.
 *
 * Deliberately the same rule the member app enforces: a place is held by any
 * member who has not been erased, plus every unexpired pending invitation. The
 * two apps have separate database clients, so this counts rather than asks; if
 * the rule changes, both of these move together or the console starts lying
 * about a limit it does not enforce.
 */
export async function getMemberPlaces(adminRoles: string[]) {
  assertAdmin(adminRoles)

  const [members, pendingInvites] = await Promise.all([
    db.user.count({ where: { deletedAt: null } }),
    db.invitation.count({ where: { status: 'PENDING', expiresAt: { gt: new Date() } } }),
  ])

  const taken = members + pendingInvites
  return {
    members,
    pendingInvites,
    taken,
    cap: MAX_MEMBERS,
    remaining: Math.max(0, MAX_MEMBERS - taken),
    isFull: taken >= MAX_MEMBERS,
  }
}

// ─── Invitations ──────────────────────────────────────────────────────────────

export async function listInvitations(adminRoles: string[], page = 1, limit = 20) {
  assertAdmin(adminRoles)
  const skip = (page - 1) * limit
  const [items, total] = await Promise.all([
    db.invitation.findMany({
      skip, take: limit, orderBy: { createdAt: 'desc' },
      select: {
        id: true, firstName: true, lastName: true, email: true,
        phone: true, status: true, codePrefix: true, minimumAmount: true,
        expiresAt: true, acceptedAt: true, createdAt: true,
      },
    }),
    db.invitation.count(),
  ])
  return { items, total, page, limit, totalPages: Math.ceil(total / limit) }
}

export async function revokeInvitation(
  adminId: string, adminRoles: string[],
  invitationId: string, ip?: string,
) {
  assertAdmin(adminRoles)
  const invite = await db.invitation.findUnique({ where: { id: invitationId }, select: { id: true, status: true, email: true } })
  if (!invite) throw new AdminNotFoundError('Invitation not found')
  if (invite.status !== 'PENDING') throw new AdminConflictError(`Invitation is already ${invite.status}`)

  await db.invitation.update({
    where: { id: invitationId },
    data: { status: 'REVOKED', revokedById: adminId, revokedAt: new Date() },
  })

  await writeAuditLog({
    userId: adminId, action: 'ADMIN_INVITATION_REVOKED',
    entity: 'Invitation', entityId: invitationId,
    payload: { email: invite.email }, ipAddress: ip,
  })
}

export async function setMemberRole(
  adminId: string, adminRoles: string[],
  memberId: string, role: 'ADMIN' | 'MEMBER', assign: boolean, ip?: string,
) {
  assertAdmin(adminRoles)
  const roleRecord = await db.role.findUnique({ where: { name: role } })
  if (!roleRecord) throw new AdminNotFoundError(`Role ${role} not found`)

  const member = await db.user.findUnique({ where: { id: memberId }, select: { id: true } })
  if (!member) throw new AdminNotFoundError('Member not found')

  // The guards this function did not have, and the member app's copy did.
  //
  // This is the copy the console is wired to, so a sole admin could open their
  // own member page, click "Remove admin", and leave the system with no admin
  // at all — sessions ended by the roleVersion bump, sign-in refused for want
  // of the role, and no way to grant it back because granting needs an admin.
  // The protection existed; it was on the path nobody took.
  //
  // Counted only when it matters. Revoking ADMIN is rare; every other change
  // skips the query.
  const adminCount =
    role === 'ADMIN' && !assign
      ? await db.userRole.count({ where: { roleId: roleRecord.id } })
      : 0

  const refusal = refuseRoleChange({ actorId: adminId, targetId: memberId, role, assign, adminCount })
  if (refusal) throw new AdminForbiddenError(ROLE_CHANGE_REFUSAL_MESSAGE[refusal])

  if (assign) {
    await db.userRole.upsert({
      where: { userId_roleId: { userId: memberId, roleId: roleRecord.id } },
      create: { userId: memberId, roleId: roleRecord.id },
      update: {},
    })
  } else {
    await db.userRole.deleteMany({ where: { userId: memberId, roleId: roleRecord.id } })
  }

  const updated = await db.user.update({
    where: { id: memberId },
    data: { roleVersion: { increment: 1 } },
    select: { id: true, roleVersion: true },
  })

  // The member portal's Edge middleware reads Redis, not Postgres. Publish the
  // version generated by this write so an old JWT is rejected immediately.
  await publishRoleVersion(updated.id, updated.roleVersion)

  await writeAuditLog({
    // ADMIN_ROLE_REVOKED, matching the member app. This wrote
    // ADMIN_ROLE_REMOVED, so an audit query filtering on the member app's name
    // silently missed every revocation the console actually performed — and the
    // console is the only place revocations happen.
    userId: adminId, action: assign ? 'ADMIN_ROLE_ASSIGNED' : 'ADMIN_ROLE_REVOKED',
    entity: 'User', entityId: memberId,
    payload: { role, assign }, ipAddress: ip,
  })

  return { memberId, role, assigned: assign }
}

export async function getMemberLoginHistory(
  adminRoles: string[], memberId: string, page = 1, limit = 20,
) {
  assertAdmin(adminRoles)
  const skip = (page - 1) * limit

  const [items, total] = await Promise.all([
    db.loginHistory.findMany({
      where: { userId: memberId },
      skip, take: limit,
      orderBy: { createdAt: 'desc' },
      select: { id: true, ipAddress: true, userAgent: true, success: true, createdAt: true },
    }),
    db.loginHistory.count({ where: { userId: memberId } }),
  ])

  return { items, total, page, limit, totalPages: Math.ceil(total / limit) }
}
